### ISSUE TITLE
Should we subclass RichText directly?

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#71]
If we subclass richtext, we limit our ability to add new fields in future.
```
class SomeTextBlock(RichTextBlock):
    class Meta:
        template = ...
```

Would it be better to create a struct block with one richtext field instead?
```py
class SomeTextBlock(StructBlock):
    body = RichTextBlock()
    class Meta:
        template = ...
```

**Comment by damonjagger** [comment]
You could use groups of blocks instead of referencing blocks directly in a page model. We've been doing that for a while and it works quite well.

### Example

`/blocks/content_blocks.py`
```
class SomeTextBlock(RichTextBlock):
    class Meta:
        template = ...
```

`/blocks/__init__.py`
```
from .content_blocks import *

CONTENT_STREAMBLOCKS = [
    ('rich_text', SomeRichTextBlock()),
]
```

Then you can just use these in your streamfield definitions anywhere, but add to them later.

```
body = StreamField(CONTENT_STREAMBLOCKS)
```

Really useful pattern for things like content blocks, which you probably want to be present in every page. Only drawback is that managing migrations can be a bit tricky, each change to the group of blocks will trigger a migration in the apps consuming the blocks.

Curious what you go with. Looking great!

**Comment by mikemonteith** [comment]
@damonjagger we do this on nhs.uk CMS too, and should probably add that pattern into this library for convenience.
I don't see how that answers the original problem of _this_ issue though.

**Comment by damonjagger** [comment]
No worries. I think I misunderstood what you wanted to achieve.

If you plan to require additional content alongside all richtext in the future then it makes sense and will save you some work later on. We do a similar pattern on a per-component basis as it's quite rare we come across that requirement.

Love to hear your thoughts if you get a minute to elaborate.
